import { addDays, set } from "date-fns";

const today = new Date();

const todayAt = (hours: number, minutes: number) =>
  set(today, { hours, minutes, seconds: 0, milliseconds: 0 }).toISOString();

export const demoBookings = [
  {
    id: "demo-1",
    customer_name: "Marcus Webb",
    customer_phone: "+14439551234",
    customer_email: "marcus@example.com",
    appointment_start: todayAt(9, 0),
    appointment_end: todayAt(11, 30),
    vehicle_type: "suv",
    notes: "Priority detail before client pickup",
    price_cents: 30000,
    status: "confirmed",
    services: { name: "World Class Complete" },
    locations: { name: "World Class - Pikesville", slug: "pikesville", address: "1210 DeRisio Lane, Pikesville, MD 21208" },
  },
  {
    id: "demo-2",
    customer_name: "Diane Foster",
    customer_phone: "+14435559876",
    customer_email: "alicia@example.com",
    appointment_start: todayAt(11, 30),
    appointment_end: todayAt(13, 30),
    vehicle_type: "sedan",
    notes: "Waits on-site",
    price_cents: 18500,
    status: "confirmed",
    services: { name: "Interior Deep Clean" },
    locations: { name: "World Class - Towson", slug: "towson", address: "1 West Pennsylvania Ave, Towson Commons Garage Level 1A, Towson, MD 21204" },
  },
  {
    id: "demo-3",
    customer_name: "Troy Hammond",
    customer_phone: "+14437771212",
    customer_email: null,
    appointment_start: todayAt(13, 0),
    appointment_end: todayAt(15, 30),
    vehicle_type: "truck",
    notes: "Exterior wax protection package",
    price_cents: 22500,
    status: "confirmed",
    services: { name: "Exterior Wax Protection" },
    locations: { name: "World Class - Mobile", slug: "mobile", address: "Mobile - serves 25-mile radius from Pikesville" },
  },
  {
    id: "demo-4",
    customer_name: "Lisa Carrington",
    customer_phone: "+14436660111",
    customer_email: "lisa@example.com",
    appointment_start: todayAt(15, 30),
    appointment_end: todayAt(17, 0),
    vehicle_type: "sedan",
    notes: "Fast turnaround needed",
    price_cents: 9900,
    status: "confirmed",
    services: { name: "Express Detail" },
    locations: { name: "World Class - Pikesville", slug: "pikesville", address: "1210 DeRisio Lane, Pikesville, MD 21208" },
  },
  {
    id: "demo-5",
    customer_name: "Stephanie Moore",
    customer_phone: "+14434445555",
    customer_email: "stephanie@example.com",
    appointment_start: todayAtDate(1, 9, 0).toISOString(),
    appointment_end: todayAtDate(1, 12, 0).toISOString(),
    vehicle_type: "suv",
    notes: "Pre-sale refresh",
    price_cents: 30000,
    status: "confirmed",
    services: { name: "World Class Complete" },
    locations: { name: "World Class - Pikesville", slug: "pikesville", address: "1210 DeRisio Lane, Pikesville, MD 21208" },
  },
  {
    id: "demo-6",
    customer_name: "Darnell Hughes",
    customer_phone: "+14433334444",
    customer_email: null,
    appointment_start: todayAtDate(1, 11, 0).toISOString(),
    appointment_end: todayAtDate(1, 13, 30).toISOString(),
    vehicle_type: "sedan",
    notes: "Interior cleanup",
    price_cents: 18500,
    status: "confirmed",
    services: { name: "Interior Deep Clean" },
    locations: { name: "World Class - Towson", slug: "towson", address: "1 West Pennsylvania Ave, Towson Commons Garage Level 1A, Towson, MD 21204" },
  },
] as const;

function todayAtDate(dayOffset: number, hours = 9, minutes = 0) {
  return set(addDays(today, dayOffset), { hours, minutes, seconds: 0, milliseconds: 0 });
}

export const demoLocations = [
  {
    id: "loc-1",
    name: "World Class - Pikesville",
    slug: "pikesville",
    address: "1210 DeRisio Lane, Pikesville, MD 21208",
    same_day_cutoff_time: null,
    hours: [
      { day_of_week: 0, is_closed: true, open_time: null, close_time: null },
      { day_of_week: 1, is_closed: false, open_time: "09:00", close_time: "17:00" },
      { day_of_week: 2, is_closed: false, open_time: "09:00", close_time: "17:00" },
      { day_of_week: 3, is_closed: false, open_time: "09:00", close_time: "17:00" },
      { day_of_week: 4, is_closed: false, open_time: "09:00", close_time: "17:00" },
      { day_of_week: 5, is_closed: false, open_time: "09:00", close_time: "17:00" },
      { day_of_week: 6, is_closed: false, open_time: "09:00", close_time: "17:00" },
    ],
    overrides: [],
  },
  {
    id: "loc-2",
    name: "World Class - Towson",
    slug: "towson",
    address: "1 West Pennsylvania Ave, Towson Commons Garage Level 1A, Towson, MD 21204",
    same_day_cutoff_time: null,
    hours: [
      { day_of_week: 0, is_closed: true, open_time: null, close_time: null },
      { day_of_week: 1, is_closed: false, open_time: "09:00", close_time: "17:00" },
      { day_of_week: 2, is_closed: false, open_time: "09:00", close_time: "17:00" },
      { day_of_week: 3, is_closed: false, open_time: "09:00", close_time: "17:00" },
      { day_of_week: 4, is_closed: false, open_time: "09:00", close_time: "17:00" },
      { day_of_week: 5, is_closed: false, open_time: "09:00", close_time: "17:00" },
      { day_of_week: 6, is_closed: false, open_time: "09:00", close_time: "17:00" },
    ],
    overrides: [{ override_date: addDays(today, 2).toISOString().slice(0, 10), is_closed: true, reason: "Garage maintenance" }],
  },
  {
    id: "loc-3",
    name: "World Class - Mobile",
    slug: "mobile",
    address: "Mobile - serves 25-mile radius from Pikesville",
    same_day_cutoff_time: "14:00",
    hours: [
      { day_of_week: 0, is_closed: true, open_time: null, close_time: null },
      { day_of_week: 1, is_closed: false, open_time: "09:00", close_time: "17:00" },
      { day_of_week: 2, is_closed: false, open_time: "09:00", close_time: "17:00" },
      { day_of_week: 3, is_closed: false, open_time: "09:00", close_time: "17:00" },
      { day_of_week: 4, is_closed: false, open_time: "09:00", close_time: "17:00" },
      { day_of_week: 5, is_closed: false, open_time: "09:00", close_time: "17:00" },
      { day_of_week: 6, is_closed: false, open_time: "09:00", close_time: "17:00" },
    ],
    overrides: [{ override_date: addDays(today, 1).toISOString().slice(0, 10), is_closed: false, open_time: "10:00", close_time: "16:00", reason: "Short route day" }],
  },
] as const;
